In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
'''
Correlation is a measure used to describe the linear relationship between two variables
A situation where two or more of the predictors have a strong correlation is known as multicollinearity.
for a perfect positive correlation (both variables increase or decrease together
for a perfect negative correlation (an increase in one variable causes a decrease in the other variable
A correlation value of 0 indicates that there is absolutely no correlation between both variables
The parameters that define the model architecture are referred to as hyperparameters
while the process of exploring a range of values is called hyperparameter tuning.
A polynomial regression model is considered a linear regression model that can be used when a curvilinear relationship exists between the predictors and the response variable.'''

''' A polynomial regression model is considered a linear regression model that can be used when a curvilinear relationship exists between the predictors and the response variable'''

In [8]:
data = pd.read_csv ('/content/drive/MyDrive/ALL DATASET/energydata_complete.csv')
data.describe(include='all')

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
unique,19735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-01-11 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,NaN,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,NaN,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,NaN,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,NaN,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,NaN,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,NaN,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [ ]:
data.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [ ]:
data.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [ ]:
data.shape

(19735, 29)

In [ ]:
df = pd.DataFrame(data = data, columns= data.Appliances )
print(df.describe)

<bound method NDFrame.describe of Appliances  60   60   50   50   60   50   60   60   60   70   ...  220  180  \
0           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
1           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
2           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
3           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
4           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
19730       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
19731       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
19732       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
19733       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN
19734       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN

Appliances  120  110  90   100  90   270  420  430
0           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...         ...  ...  ...  ...  ...  ...  ...  ...
19730       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
19731       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
19732       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
19733       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
19734       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[19735 rows x 19735 columns]>

In [ ]:
train  = data.drop(['date', 'lights'], axis=1)
test = data['Appliances']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, test,
test_size=0.3, random_state=42)

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
features_data = normalised_data.drop(columns=['date','light'])
heating_target = normalised_data['Apliances']

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-20-48243db5a8d3>, line 3)

In [ ]:
regss = LinearRegression()

In [ ]:
regss.fit(X_train, y_train)

LinearRegression()

In [ ]:
predct= regss.predict(X_train)
print(predct)

[ 50.  60.  50. ...  60. 210.  50.]

In [ ]:
regss.score(X_train, y_train)

1.0

In [ ]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)